

export const customStyles = {
  stepIndicatorSize: 25,
  currentStepIndicatorSize: 30,
  separatorStrokeWidth: 2,
  currentStepStrokeWidth: 3,
  stepStrokeCurrentColor: "#2c3e50",
  stepStrokeWidth: 3,
  stepStrokeFinishedColor: "#2c3e50",
  stepStrokeUnFinishedColor: "#aaaaaa",
  separatorFinishedColor: "#2c3e50",
  separatorUnFinishedColor: "#aaaaaa",
  stepIndicatorFinishedColor: "#2c3e50",
  stepIndicatorUnFinishedColor: "#ffffff",
  stepIndicatorCurrentColor: "#ffffff",
  stepIndicatorLabelFontSize: 13,
  currentStepIndicatorLabelFontSize: 13,
  stepIndicatorLabelCurrentColor: "#2c3e50",
  stepIndicatorLabelFinishedColor: "#ffffff",
  stepIndicatorLabelUnFinishedColor: "#aaaaaa",
  labelColor: "#999999",
  labelSize: 13,
  currentStepLabelColor: "#2c3e50",
};
